CREATE DATABASE BTD210_Asg2_Grp4;

CREATE TABLE AIRLINE(
AIRLINE_CODE VARCHAR(2) PRIMARY KEY,
AIRLINE_NAME VARCHAR(20));

CREATE TABLE AIRCRAFT(
AIRCRAFT_CODE INT PRIMARY KEY,
AIRCRAFT_DESC VARCHAR(100));

CREATE TABLE AIRPORT(
AIRPORT_CODE VARCHAR(5) PRIMARY KEY,
AIRPORT_NAME VARCHAR(100),
AIRPORT_CITY VARCHAR(100)
);

CREATE TABLE FLIGHT(
FLIGHT_NUM VARCHAR(7) PRIMARY KEY,
AIRLINE_CODE VARCHAR(2),
AIRCRAFT_CODE  INT,
OPERATED_BY VARCHAR(5),
DEP_AIRPORT_CODE VARCHAR(),
ARR_AIRPORT_CODE VARCHAR(10),
FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
FOREIGN KEY (AIRCRAFT_CODE) REFERENCES AIRCRAFT(AIRCRAFT_CODE),
FOREIGN KEY (OPERATED_BY) REFERENCES AIRLINES(AIRLINE_CODE),
FOREIGN KEY (DEP_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY (ARR_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
);